apiVersion: v1
kind: Service
metadata:
  name: messaging-api
spec:
  type: NodePort
  selector:
    app: messaging-api
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort boş bırakıldı; K8s otomatik atar (30000-32767)
