apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging-uat

resources:
  - ../../base
patches:
  - path: service-patch.yaml
configMapGenerator:
  - name: messaging-api-env
    literals:
      - ENVIRONMENT=uat

images:
  - name: apinizeren/messaging
    newTag: latest
